import { test, expect } from '@playwright/test';
import { API, prepareTestRepo } from './helpers';

test('Sonail imports a manual plan, explains dependencies and switches language without a model call', async ({ page, request }) => {
  const repoPath = prepareTestRepo('sonail-manual-onboarding', { clean: true });
  const projectRes = await request.post(`${API}/api/projects`, { data: { name: 'Sonail onboarding', repoPath, defaultAgentType: 'opencode', defaultUseWorktree: true } });
  expect(projectRes.ok()).toBeTruthy();
  const project = await projectRes.json();
  const emptyProjectRes = await request.post(`${API}/api/projects`, { data: { name: 'Sonail no repository' } });
  expect(emptyProjectRes.ok()).toBeTruthy();
  const emptyProject = await emptyProjectRes.json();
  try {
    await page.goto('/workbench');
    await expect(page.getByLabel('选择项目')).toBeVisible();
    await page.getByLabel('选择项目').selectOption(emptyProject.id);
    await page.getByRole('button', { name: '使用指引', exact: true }).click();
    await expect(page.locator('.sb-guide').getByRole('button', { name: '新建项目', exact: true })).toBeVisible();
    await expect(page.getByRole('button', { name: '载入两任务示例', exact: true })).toBeDisabled();
    await page.getByLabel('选择项目').selectOption(project.id);
    await page.getByRole('button', { name: '使用指引', exact: true }).click();
    await expect(page.getByRole('heading', { name: '不用懂代码，也能掌握项目进展', exact: true })).toBeVisible();
    await expect(page.getByText(repoPath, { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '配置角色', exact: true }).click();
    await expect(page.getByRole('heading', { name: '三个角色，分别配置', exact: true })).toBeVisible();
    await page.getByRole('button', { name: '使用指引', exact: true }).click();
    await page.getByRole('button', { name: '载入两任务示例', exact: true }).click();
    await expect(page.getByLabel('任务方案 JSON')).toBeVisible();
    expect(JSON.parse(await page.getByLabel('任务方案 JSON').inputValue()).tasks).toHaveLength(2);
    const beforeImport = await (await request.get(`${API}/api/workflow/${project.id}`)).json();
    expect(Object.keys(beforeImport.tasks)).toHaveLength(0);
    await page.getByRole('button', { name: '预览导入方案', exact: true }).click();
    await expect(page.getByRole('heading', { name: '这是不是你想要的结果？', exact: true })).toBeVisible();
    const staged = await (await request.get(`${API}/api/workflow/${project.id}`)).json();
    expect(staged.proposal.tasks).toHaveLength(2);
    expect(Object.keys(staged.tasks)).toHaveLength(0);
    await expect(page.getByText('等待：01 · 项目简介', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: '符合我的想法，发布任务', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('方案已确认，任务卡已发布');
    await page.getByRole('button', { name: '任务看板', exact: true }).click();
    await expect(page.getByRole('button', { name: '01 · 项目简介', exact: true })).toBeVisible();
    await expect(page.getByText('等待上游合入', { exact: true })).toBeVisible();
    const state = await (await request.get(`${API}/api/workflow/${project.id}`)).json();
    expect(state.autonomous).toBe(false);
    expect(state.autoAccept).toBe(false);
    expect(Object.values(state.tasks).every((t: any) => t.phase === 'ready' && !t.acceptedAt)).toBeTruthy();
    await page.getByRole('button', { name: '01 · 项目简介', exact: true }).click();
    await page.getByText('原始执行过程（高级）', { exact: true }).click();
    await page.getByRole('button', { name: '详细执行过程', exact: true }).click();
    await expect(page.locator('#agent-panel').getByRole('button', { name: '执行记录', exact: true })).toBeVisible();
    await expect(page.locator('#agent-panel').getByRole('button', { name: '任务说明', exact: true })).toBeVisible();
    await page.getByTitle('关闭详情（Esc）', { exact: true }).click();
    await expect(page.locator('#agent-panel')).not.toBeVisible();
    await page.locator('.sb-drawer > header .sb-icon').click();
    await page.getByRole('button', { name: 'English', exact: true }).click();
    await expect(page.getByRole('navigation').getByRole('button', { name: 'Manager records', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Getting started', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Keep control without reading every line of code', exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Continue current work', exact: true }).click();
    await page.getByRole('button', { name: '01 · 项目简介', exact: true }).click();
    await page.getByText('Raw execution activity (advanced)', { exact: true }).click();
    await page.getByRole('button', { name: 'Detailed execution', exact: true }).click();
    await expect(page.locator('#agent-panel').getByRole('button', { name: 'Events', exact: true })).toBeVisible();
    await page.getByTitle('Close panel (Esc)', { exact: true }).click();
    await expect(page.locator('#agent-panel')).not.toBeVisible();
    await page.locator('.sb-drawer > header .sb-icon').click();
    await page.getByRole('button', { name: 'Integrations & appearance', exact: true }).click();
    await expect(page.getByRole('heading', { name: 'Service & startup', exact: true })).toBeVisible();
  } finally {
    await request.delete(`${API}/api/projects/${project.id}`);
    await request.delete(`${API}/api/projects/${emptyProject.id}`);
  }
});
