import { useEffect, useState } from 'react';
import { integrationSlots, type WorkbenchSettings } from '../../../../shared/workbench';
import ServiceSettings from './ServiceSettings';
import ToolsDirectorySettings from './ToolsDirectorySettings';
type Translate = (zh: string, en: string) => string;
export default function IntegrationSettings({ value, t, pending, onSave, onNotice, children }: { value: WorkbenchSettings; t: Translate; pending: boolean; onSave: (value: WorkbenchSettings) => void; onNotice: (message: string) => void; children: React.ReactNode }) {
  const [theme, setTheme] = useState(value.theme); const [search, setSearch] = useState('');
  const [quotaVisibility, setQuotaVisibility] = useState(value.quotaVisibility || 'auto');
  const [resetForecast, setResetForecast] = useState(!!value.resetForecast);
  useEffect(() => setTheme(value.theme), [value.theme]);
  useEffect(() => { if (!pending) { setQuotaVisibility(value.quotaVisibility || 'auto'); setResetForecast(!!value.resetForecast); } }, [pending, value.quotaVisibility, value.resetForecast]);
  const matches = (keywords: string) => !search.trim() || keywords.toLowerCase().includes(search.trim().toLowerCase());
  return <div className="sb-settings"><input className="sb-setting-search" aria-label={t('搜索集成设置', 'Search integration settings')} placeholder={t('搜索外观、接口、插件、启动…', 'Search appearance, endpoints, plugins, startup…')} value={search} onChange={e => setSearch(e.target.value)} />
    <section className="sb-sheet" hidden={!matches('服务 启动 开机 登录 自动 桌面 持久化 数据 service startup autostart desktop launch data')}><ServiceSettings t={t} onNotice={onNotice} /></section>
    <section className="sb-sheet" hidden={!matches('外观 风格 配色 主题 亮色 appearance theme color palette')}><h2>{t('全局外观', 'Global appearance')}</h2><p className="sb-muted">{t('所有项目共用亮色主题。模型与授权仍在各自项目中配置。', 'Light theme applies to all projects. Models and permissions are configured per project.')}</p><div className="sb-theme-options">{([['sage', '鼠尾草 · 清爽', 'Sage'], ['warm', '暖纸 · 柔和', 'Warm paper'], ['indigo', '鸢尾 · 明快', 'Iris']] as const).map(([id, zh, en]) => <button key={id} className={`sb-theme-choice sb-theme-${id}`} aria-pressed={theme === id} onClick={() => setTheme(id)}><span /><strong>{t(zh, en)}</strong><small>{theme === id ? t('已选择', 'Selected') : t('选择主题', 'Choose theme')}</small></button>)}</div><button className="sb-button sb-primary" disabled={pending} onClick={() => onSave({ theme })}>{t('保存全局外观', 'Save appearance')}</button></section>
    <section className="sb-sheet" hidden={!matches('Codex 额度 悬浮卡 预测 刷新 信号 quota floating forecast reset')}><h2>{t('Codex 额度与刷新', 'Codex quota & reset outlook')}</h2><p className="sb-muted">{t('读取本机已登录的 Codex，不发起模型调用。悬浮卡的隐藏与这里同步。', 'Reads signed-in local Codex without model calls. Visibility stays synchronized with the card.')}</p><label>{t('悬浮卡显示方式', 'Quota card visibility')}<select aria-label={t('悬浮卡显示方式', 'Quota card visibility')} value={quotaVisibility} disabled={pending} onChange={e => { setQuotaVisibility(e.target.value as NonNullable<WorkbenchSettings['quotaVisibility']>); onSave({ ...value, quotaVisibility: e.target.value as WorkbenchSettings['quotaVisibility'] }); }}><option value="auto">{t('配置了 Codex 角色时自动显示', 'Automatic when a role uses Codex')}</option><option value="shown">{t('始终显示', 'Always show')}</option><option value="hidden">{t('隐藏', 'Hidden')}</option></select></label><label className="sb-check"><input type="checkbox" checked={resetForecast} disabled={pending} onChange={e => { setResetForecast(e.target.checked); onSave({ ...value, resetForecast: e.target.checked }); }} />{t('开启社区刷新预测', 'Enable community reset forecast')}</label><p className="sb-muted">{t('开启后，显示卡片时才读取 codex-reset.com 的公开数据，不向它发送账户用量或凭据。概率是社区预测，不能保证刷新。', 'When enabled, a visible card reads public codex-reset.com data without sending account usage or credentials. It is a community forecast, not a guaranteed reset.')}</p></section>
    <section className="sb-sheet" hidden={!matches('工具 安装 目录 路径 tools installation directory path')}><ToolsDirectorySettings value={value} t={t} pending={pending} onSave={onSave} /></section>
    <div hidden={!matches('接口 提供方 密钥 本地 模型 自定义 OpenAI Anthropic API key local provider endpoint')}>{children}</div>
    <section className="sb-sheet" hidden={!matches('插件 模块 扩展 余额 额度 刷新 集成 plugin module integration balance quota reset')}><h2>{t('模块与二次开发', 'Modules & extensions')}</h2><p>{t('当前支持源代码扩展与标准适配器接口。第三方可实现模块再编译接入；暂不加载任意插件文件。', 'Source extensions and versioned adapter contracts are available. Third parties implement and compile modules; arbitrary plugin loading is not available.')}</p><div className="sb-module-grid">{integrationSlots.map(slot => <article key={slot.id}><strong>{slot.id === 'balance' ? t('余额与额度', 'Balance & quota') : t('刷新信号', 'Reset signals')}</strong><span>{slot.status === 'available' ? t('已接入 · 可选开启', 'Available · optional') : t('接口预留 · 待开发', 'Contract reserved · future')}</span><p>{slot.id === 'balance' ? t('未来独立接入提供方余额；现在不调用接口、不消耗额度。', 'Future provider balance module. No requests or credits used now.') : t('通过可替换适配器接入 codex-reset.com，保留来源时间与不确定性。', 'Replaceable codex-reset.com adapter with source timestamps and uncertainty.')}</p></article>)}</div><p className="sb-muted">{t('开发契约：shared/workbench.ts · IntegrationAdapter<T> · apiVersion 1。权限、密钥、版本兼容和错误隔离需要由实际模块实现并审核。', 'Contract: shared/workbench.ts · IntegrationAdapter<T> · apiVersion 1. Actual modules must implement and review permissions, secrets, compatibility and failure isolation.')}</p></section>
  </div>;
}
