import { Suspense, lazy, useEffect, useRef, useState } from 'react';
import { DndContext, KeyboardSensor, MouseSensor, TouchSensor, useDraggable, useDroppable, useSensor, useSensors, type DragEndEvent } from '@dnd-kit/core';
import { ArrowUpRight, Check, ChevronRight, CircleHelp, Columns3, FileText, GripVertical, Layers3, LoaderCircle, Plus, RefreshCw, Settings2, ShieldCheck, Sparkles, Square, X } from 'lucide-react';
import { api, connectWS } from '@/lib/api';
import type { Project, Task } from '@/types';
import { defaults, findingText, isBlockingFinding, type Assessment, type Criterion, type Endpoint, type ProjectWorkflow, type Proposal, type Role, type RoleProfile } from '../../../../shared/workflow';
import './workbench.css';
import './project-hub.css';
import ProjectHub from './ProjectHub';
import IntegrationSettings from './IntegrationSettings';
import UsageGuide from './UsageGuide';
import AiAccess from './AiAccess';
import QuotaCard from './QuotaCard';
import PlanPreview from './PlanPreview';
import demoZh from '../../../../examples/demo.zh-CN.json?raw';
import demoEn from '../../../../examples/demo.en.json?raw';
import type { WorkbenchSettings, ProjectMeta } from '../../../../shared/workbench';
const AgentPanel = lazy(() => import('./AgentPanel').then(module => ({ default: module.AgentPanel })));
const ArtifactPreview = lazy(() => import('./ArtifactPreview'));

type Tab = 'projects' | 'board' | 'manager' | 'spec' | 'settings' | 'integrations' | 'guide';
type Translate = (zh: string, en: string) => string;
const lanes = ['backlog', 'in-progress', 'review', 'done'] as const;
const roleNames = { manager: ['项目经理', 'Project manager'], executor: ['执行者', 'Executor'], reviewer: ['独立审查者', 'Independent reviewer'] };
const phaseNames: Record<string, string[]> = { ready: ['待执行', 'Ready'], executing: ['执行中', 'Executing'], reviewing: ['独立审查中', 'Reviewing'], 'manager-check': ['经理把关中', 'Manager check'], 'awaiting-user': ['等你体验确认', 'Your confirmation'], 'needs-changes': ['需要返工', 'Needs changes'], blocked: ['需要处理', 'Blocked'], failed: ['运行失败', 'Failed'], accepted: ['已验收，待合入', 'Accepted, not integrated'], integrated: ['已验收并合入', 'Integrated'], interrupted: ['运行已中断', 'Interrupted'], 'spec-changed': ['规格变化，需复核', 'Specification changed'], 'dependency-invalidated': ['上游变化，需复核', 'Upstream changed'], 'review-ready': ['等待审查', 'Ready for review'], 'integration-blocked': ['合入需处理', 'Integration blocked'] };
async function request<T>(url: string, method = 'GET', body?: unknown): Promise<T> {
  const key = import.meta.env.VITE_API_KEY;
  const res = await fetch(`/api/workflow${url}`, { method, headers: { 'Content-Type': 'application/json', ...(key ? { Authorization: `Bearer ${key}` } : {}) }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const data = await res.json(); if (!res.ok) throw new Error(data.error || `HTTP ${res.status}`); return data;
}
function Lane({ id, title, count, children }: { id: string; title: string; count: number; children: React.ReactNode }) {
  const { setNodeRef, isOver } = useDroppable({ id });
  return <section ref={setNodeRef} className={`sb-lane ${isOver ? 'sb-over' : ''}`}><h3><span className={`sb-dot sb-dot-${id}`} />{title}<span className="sb-count">{count.toString().padStart(2, '0')}</span></h3>{children}</section>;
}
function Card({ task, phase, blocked, t, onClick, onMerge, pending }: { task: Task; phase: string; blocked: boolean; t: Translate; onClick: () => void; onMerge?: () => void; pending: boolean }) {
  const { attributes, listeners, setNodeRef, isDragging } = useDraggable({ id: task.id });
  return <article ref={setNodeRef} className={`sb-card ${isDragging ? 'sb-dragging' : ''}`}>
    <div className="sb-card-top"><span>{task.id.slice(0, 6).toUpperCase()}</span><button className="sb-icon" aria-label={t('拖拽任务', 'Drag task')} {...attributes} {...listeners}><GripVertical size={16} /></button></div>
    <button className="sb-card-title" onClick={onClick}>{task.title}</button><p>{task.description.slice(0, 95)}</p>
    <div className="sb-card-bottom"><span className={`sb-phase ${blocked ? 'sb-warning' : ''}`}>{blocked ? t('等待上游合入', 'Waiting for dependencies') : phase}</span><button className="sb-icon" title={t('查看任务与验收', 'View task and review')} onClick={onClick}><ChevronRight size={17} /></button></div>
    {onMerge && <button className="sb-button sb-primary sb-card-merge" disabled={pending} title={t('验收已通过；合入后解锁下游。服务端会重新检查审查与版本。', 'Accepted; integration unlocks downstream. Reviews and revisions are rechecked.')} onClick={onMerge}><Check size={14} />{t('合入项目', 'Integrate')}</button>}
  </article>;
}
function ProfileEditor({ name, value, endpoints, t, onChange }: { name: string; value: RoleProfile; endpoints: Endpoint[]; t: Translate; onChange: (p: RoleProfile) => void }) {
  const change = (patch: Partial<RoleProfile>) => onChange({ ...value, ...patch });
  return <section className="sb-profile"><h3>{name}</h3><div className="sb-fields">
    <label>{t('执行工具', 'Harness')}<select value={value.harness} onChange={e => change({ harness: e.target.value as RoleProfile['harness'], endpointId: undefined })}><option value="opencode">OpenCode</option><option value="codex">Codex</option><option value="claude">Claude Code</option><option value="dsh">DeepSeek Harness</option></select></label>
    <label>{t('模型 ID，可输入免费或本地模型', 'Model ID, including free or local models')}<input value={value.model} onChange={e => change({ model: e.target.value })} placeholder={value.harness === 'opencode' ? 'opencode/space-bunny-free' : 'model-id'} /></label>
    <label>{t('思考等级', 'Reasoning effort')}<select value={value.effort} onChange={e => change({ effort: e.target.value })}>{['default', 'low', 'medium', 'high', 'xhigh', 'max'].map(x => <option key={x} value={x} disabled={x !== 'default' && (!!value.endpointId || (value.harness === 'codex' && x === 'max'))}>{x === 'default' ? t('模型默认', 'Model default') : x}</option>)}</select></label>
    <label>{t('超时（分钟）', 'Timeout (minutes)')}<input type="number" min="1" max="180" value={value.timeoutMinutes} onChange={e => change({ timeoutMinutes: Number(e.target.value) })} /></label>
    {value.harness === 'opencode' && <label>{t('模型来源', 'Model source')}<select value={value.endpointId || ''} onChange={e => change({ endpointId: e.target.value || undefined, ...(e.target.value ? { effort: 'default' } : {}) })}><option value="">{t('OpenCode 已配置提供方', 'OpenCode configured providers')}</option>{endpoints.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label>}
  </div><label className="sb-check"><input type="checkbox" checked={value.auto} onChange={e => change({ auto: e.target.checked })} />{t('由经理按任务复杂度选档', 'Select tier by task complexity')}</label>
    {value.auto && <><p className="sb-muted">{t('只从下面允许的模型中选；从轻量到强力排列。关闭自动即使用上面的手动选择。', 'Only choose from your allowed list, ordered from lightweight to strongest. Manual selection applies when auto is off.')}</p>{value.candidates.map((c, i) => <div className="sb-candidate" key={i}><input aria-label={t('候选模型', 'Candidate model')} value={c.model} onChange={e => change({ candidates: value.candidates.map((v, n) => n === i ? { ...v, model: e.target.value } : v) })} /><select aria-label={t('候选思考等级', 'Candidate effort')} value={c.effort} onChange={e => change({ candidates: value.candidates.map((v, n) => n === i ? { ...v, effort: e.target.value } : v) })}>{['default', 'low', 'medium', 'high', 'xhigh', 'max'].map(x => <option key={x}>{x}</option>)}</select><button className="sb-icon" title={t('移除候选模型', 'Remove candidate')} onClick={() => change({ candidates: value.candidates.filter((_, n) => n !== i) })}><X size={16} /></button></div>)}<button className="sb-button sb-small" onClick={() => change({ candidates: [...value.candidates, { model: value.model, effort: value.effort, endpointId: value.endpointId }] })}><Plus size={14} />{t('添加允许模型', 'Add allowed model')}</button></>}
  </section>;
}
function Review({ title, result, t }: { title: string; result?: Assessment; t: Translate }) {
  return <section className="sb-review"><h3><ShieldCheck size={17} />{title}{result && <span className={`sb-verdict sb-verdict-${result.verdict}`}>{result.verdict === 'pass' ? t('推荐通过', 'Recommended') : result.verdict === 'revise' ? t('安排返工', 'Revision') : t('暂不能推进', 'Blocked')}</span>}</h3>{!result ? <p className="sb-muted">{t('尚无审查结论', 'No review yet')}</p> : <><p className="sb-review-summary">{result.summary}</p>{!!result.humanChecks.length && <div className="sb-human"><strong>{t('需要你实际体验', 'Your experience is needed')}</strong>{result.humanChecks.map((s, i) => <p key={i}>{s}</p>)}</div>}<details><summary>{t('逐条证据与建议', 'Evidence and suggestions')}</summary>{result.criteria.map(c => <div className="sb-evidence" key={c.id}><strong>{c.id} · {c.status === 'human' ? t('等你体验', 'Your experience') : c.status === 'pass' ? t('已核验', 'Verified') : c.status}</strong><span>{c.evidence}</span></div>)}{result.findings.map((s, i) => <p className={isBlockingFinding(s) ? 'sb-warning' : 'sb-muted'} key={i}><strong>{isBlockingFinding(s) ? t('阻塞：', 'Blocking: ') : t('可选建议 · 不影响通过：', 'Optional, does not block: ')}</strong>{findingText(s)}</p>)}{result.revision && <p>{t('执行者修改意见：', 'Executor guidance: ')}{result.revision}</p>}</details></> }</section>;
}

export function Workbench() {
  const [lang, setLang] = useState(() => localStorage.getItem('sonail.language') || 'zh');
  const t: Translate = (zh, en) => lang === 'zh' ? zh : en;
  const [tab, setTab] = useState<Tab>('projects'); const [projects, setProjects] = useState<Project[]>([]);
  const [projectId, setProjectId] = useState(() => localStorage.getItem('sonail.project') || '');
  const [workflow, setWorkflow] = useState<ProjectWorkflow>(defaults); const [draft, setDraft] = useState<ProjectWorkflow>(defaults);
  const [tasks, setTasks] = useState<Task[]>([]); const [endpoints, setEndpoints] = useState<Endpoint[]>([]);
  const [selected, setSelected] = useState(''); const [detail, setDetail] = useState<Task | null>(null);
  const [notice, setNotice] = useState(''); const [pending, setPending] = useState(false); const [newProject, setNewProject] = useState(false);
  const [newName, setNewName] = useState(''); const [newPath, setNewPath] = useState('');
  const [endpoint, setEndpoint] = useState<Endpoint>({ id: '', name: '', protocol: 'openai', baseUrl: 'http://127.0.0.1:11434/v1', apiKey: '' });
  const [edit, setEdit] = useState<{ title: string; description: string; criteria: Criterion[]; override?: RoleProfile } | null>(null);
  const [reason, setReason] = useState(''); const [json, setJson] = useState(''); const [events, setEvents] = useState<{ type: string; content: string; timestamp: number }[]>([]);
  const [ascending, setAscending] = useState(true); const [search, setSearch] = useState('');
  const [settingsSearch, setSettingsSearch] = useState('');
  const [manualImportOpen, setManualImportOpen] = useState(false);
  const [appearance, setAppearance] = useState<WorkbenchSettings>({ theme: 'sage' });
  const [archived, setArchived] = useState(false);
  const [hubRevision, setHubRevision] = useState(0);
  const [artifacts, setArtifacts] = useState<{ path: string; content?: string; note?: string }[] | null>(null);
  const managerSeen = useRef<string>('');
  const projectRef = useRef(projectId);
  const selectionRef = useRef(selected); selectionRef.current = selected;
  const refreshSequence = useRef(0);
  const matchesSetting = (keywords: string) => !settingsSearch.trim() || keywords.toLowerCase().includes(settingsSearch.toLowerCase().trim());
  const logRef = useRef<HTMLDivElement>(null); const follow = useRef(true);
  const sensors = useSensors(useSensor(MouseSensor, { activationConstraint: { distance: 7 } }), useSensor(TouchSensor, { activationConstraint: { delay: 200, tolerance: 5 } }), useSensor(KeyboardSensor));
  const project = projects.find(p => p.id === projectId);
  const task = tasks.find(t => t.id === selected); const policy = workflow.tasks[selected];
  const refresh = async (id = projectId, resetDraft = false, switchTo = false) => {
    if (!switchTo && id && projectRef.current && projectRef.current !== id) return;
    const sequence = ++refreshSequence.current;
    const ps = await api.getProjects();
    if (sequence !== refreshSequence.current || (!switchTo && projectRef.current !== id)) return;
    setProjects(ps);
    const chosen = ps.find(p => p.id === id)?.id || ps.find(p => !p.isDefault)?.id || ps[0]?.id;
    if (!chosen) return;
    projectRef.current = chosen;
    const [wf, ts, ep, globalSettings] = await Promise.all([request<ProjectWorkflow & { projectMeta: ProjectMeta }>(`/${chosen}`), api.getTasks(false, chosen), request<Endpoint[]>('/endpoints'), request<WorkbenchSettings>('/settings')]).catch(error => { if (sequence === refreshSequence.current) projectRef.current = projectId; throw error; });
    if (sequence !== refreshSequence.current || projectRef.current !== chosen) return;
    if (chosen !== projectId) setProjectId(chosen);
    setWorkflow(wf); setTasks(ts); setEndpoints(ep); setAppearance(globalSettings); setArchived(!!wf.projectMeta?.archivedAt); if (resetDraft) setDraft(structuredClone(wf));
    return { workflow: wf, tasks: ts };
  };
  const work = async (fn: () => Promise<unknown>, success: string, refreshAfter = true) => { const origin = projectRef.current; setPending(true); try { await fn(); if (refreshAfter) await refresh(); if (!refreshAfter || projectRef.current === origin) setNotice(success); } catch (e) { if (projectRef.current === origin) setNotice((e as Error).message); } finally { setPending(false); } };
  const action = (name: string, body: unknown = {}, success = t('操作已完成', 'Action completed')) => work(() => { if (archived && name !== 'pause') throw new Error(t('项目已归档。请在项目总览的「已归档」中恢复后再操作。', 'Project archived. Restore it from the Archived project overview first.')); return request(`/${projectId}/${name}`, 'POST', body); }, success);
  useEffect(() => { document.documentElement.classList.remove('dark'); document.documentElement.classList.add('light'); localStorage.setItem('sonail.language', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; }, [lang]);
  useEffect(() => { projectRef.current = projectId; localStorage.setItem('sonail.project', projectId); void refresh(projectId, true).catch(e => setNotice(e.message)); const unsubscribe = connectWS(() => { void refresh().catch(() => {}); }); const timer = setInterval(() => { void refresh().catch(() => {}); }, 5000); return () => { clearInterval(timer); unsubscribe(); }; }, [projectId]);
  useEffect(() => { if (task) setEdit({ title: task.title, description: task.description, criteria: structuredClone(policy?.criteria || []), override: policy?.override }); setReason(''); setArtifacts(null); }, [selected]);
  useEffect(() => { setEvents([]); if (!selected) return; let cancelled = false; const load = () => api.getEvents(selected).then(data => { if (!cancelled) setEvents(data); }).catch(() => {}); void load(); const timer = setInterval(load, 3000); return () => { cancelled = true; clearInterval(timer); }; }, [selected]);
  useEffect(() => { if (follow.current && logRef.current) logRef.current.scrollTop = logRef.current.scrollHeight; }, [workflow.events, events]);
  useEffect(() => {
    const latest = workflow.managerRecords?.at(-1); if (!latest) return;
    if (managerSeen.current.startsWith(`${projectId}:`) && managerSeen.current !== `${projectId}:${latest.id}` && ['assessment', 'attention', 'task-change'].includes(latest.kind)) setNotice(t('经理有新意见，请查看「经理记录」或任务详情。', 'New manager guidance is available in Manager records.'));
    managerSeen.current = `${projectId}:${latest.id}`;
  }, [workflow.managerRecords, projectId]);
  const phase = (s: string) => { const n = phaseNames[s]; return n ? t(n[0], n[1]) : s; };
  const sorted = [...tasks].filter(x => (!search || `${x.title} ${x.description}`.toLowerCase().includes(search.toLowerCase()))).sort((a, b) => (ascending ? 1 : -1) * a.title.localeCompare(b.title, 'zh', { numeric: true }));
  const progress = Object.values(workflow.tasks).filter(p => p.mergedAt && p.acceptedAt).length;
  const attentionTasks = tasks.filter(task => ['awaiting-user', 'blocked', 'failed', 'needs-changes', 'interrupted', 'integration-blocked'].includes(workflow.tasks[task.id]?.phase || ''));
  const inFlightTasks = tasks.filter(task => ['executing', 'reviewing', 'manager-check'].includes(workflow.tasks[task.id]?.phase || ''));
  const managerRecords = [...(workflow.managerRecords || [])].reverse();
  const attentionFor = (id: string) => workflow.tasks[id]?.attention || (['blocked', 'failed', 'interrupted', 'integration-blocked'].includes(workflow.tasks[id]?.phase) ? { message: [...workflow.events].reverse().find(e => e.taskId === id && e.type === 'error')?.content || t('上次运行未完成有效核对，产物已保留。', 'The last run did not complete a valid check; work is preserved.'), nextStep: t('点击「让经理重新核对」，获取明确结论；不会替你验收或删除产物。', 'Ask the manager to recheck. This does not accept or delete your work.') } : undefined);
  const taskAttention = attentionFor(selected);
  const copy = (text: string) => work(() => navigator.clipboard.writeText(text), t('已复制', 'Copied'));
  const drop = (e: DragEndEvent) => {
    const target = String(e.over?.id || ''); const id = String(e.active.id); const moved = tasks.find(t => t.id === id);
    if (!moved || target === moved.columnId) return;
    setSelected(id);
    if (target === 'in-progress') void action('start', { taskId: id }, t('已启动；可查看实时过程', 'Started; live events available'));
    else if (target === 'review') void action('review', { taskId: id }, t('已请求独立审查', 'Review requested'));
    else if (target === 'done') void action('accept', { taskId: id }, t('验收已确认', 'Acceptance confirmed'));
    else setNotice(t('重新打开需要填写原因，请在任务详情操作', 'Reopening requires a reason; use task details'));
  };
  return <div className="sb-app" data-theme={appearance.theme}><aside className="sb-sidebar"><a className="sb-brand" href="/workbench"><Layers3 size={25} /><span>sonail<small>{t('让想法稳步交付', 'Ideas into reviewed work')}</small></span></a>
    <div className="sb-project-picker"><span className="sb-eyebrow">{t('当前项目', 'PROJECT')}</span><select aria-label={t('选择项目', 'Select project')} value={projectId} onChange={e => { setProjectId(e.target.value); setSelected(''); }}>{projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="sb-sidebar-new" onClick={() => setNewProject(true)}><Plus size={15} />{t('新建项目', 'New project')}</button></div>
    <nav>{([['guide', CircleHelp, '使用指引', 'Getting started'], ['projects', Layers3, '项目总览', 'Projects'], ['board', Columns3, '任务看板', 'Task board'], ['manager', Sparkles, '经理记录', 'Manager records'], ['spec', FileText, '想法与规格', 'Idea & specification'], ['settings', Settings2, '角色与设置', 'Roles & settings'], ['integrations', Settings2, '集成与外观', 'Integrations & appearance']] as const).map(([id, Icon, zh, en]) => <button key={id} className={tab === id ? 'sb-nav-active' : ''} onClick={() => { setTab(id); setDraft(structuredClone(workflow)); }}><Icon size={18} />{t(zh, en)}{((id === 'spec' && workflow.proposal) || (id === 'manager' && attentionTasks.length > 0)) && <span className="sb-unread" />}</button>)}</nav>
    <div className="sb-sidebar-bottom"><div className="sb-manager-state"><Sparkles size={18} /><strong>{t('项目经理', 'Project manager')}</strong><span>{workflow.roles.manager.harness}</span><small>{workflow.roles.manager.model}</small></div><button onClick={() => void action('pause', {}, t('已暂停', 'Paused'))}><Square size={14} />{t('暂停项目', 'Pause project')}</button><button onClick={() => setLang(lang === 'zh' ? 'en' : 'zh')}><CircleHelp size={15} />{lang === 'zh' ? 'English' : '简体中文'}</button></div></aside>
    <main className="sb-main"><header className="sb-header"><div><div className="sb-eyebrow">{t('项目工作空间', 'PROJECT WORKSPACE')} / {String(projectId).slice(0, 8)}</div><h1>{tab === 'guide' ? t('使用指引', 'Getting started') : tab === 'projects' ? t('你的项目空间', 'Your project space') : tab === 'integrations' ? t('集成与外观', 'Integrations & appearance') : project?.name || 'Sonail'}</h1><p>{t('先把方向讲清楚，再让每一步经得起审查。', 'Clarify the goal. Execute, review, and deliver with evidence.')}</p></div><div className="sb-toolbar"><button className="sb-button" title={t('刷新所有任务与经理状态', 'Refresh all tasks and manager status')} onClick={() => void work(async () => { await refresh(); setHubRevision(n => n + 1); }, t('整个看板已刷新', 'Board refreshed'))}><RefreshCw size={16} />{t('刷新看板', 'Refresh board')}</button><a className="sb-button" href={`/projects/${projectId}`} target="_blank" rel="noreferrer">{t('原版详细视图', 'Original detailed view')}<ArrowUpRight size={15} /></a></div></header>
    {archived && tab !== 'projects' && tab !== 'integrations' && tab !== 'guide' && <div className="sb-notice"><span>{t('此项目已归档，只读查看。需要修改时，请在项目总览的「已归档」中恢复。', 'Archived project · read-only. Restore it in the Archived project overview before editing.')}</span><button className="sb-button sb-small" onClick={() => setTab('projects')}>{t('打开项目总览', 'Open project overview')}</button></div>}
    {notice && <div className="sb-notice" role="status"><span>{notice}</span><button className="sb-icon" aria-label={t('关闭提示', 'Dismiss notification')} onClick={() => setNotice('')}><X size={16} /></button></div>}
    {tab !== 'projects' && tab !== 'integrations' && tab !== 'guide' && <section className="sb-overview"><div><span className="sb-eyebrow">{t('交付进度', 'DELIVERY')}</span><strong>{progress}<small> / {Object.keys(workflow.tasks).length}</small></strong><div className="sb-progress"><i style={{ width: `${progress / Math.max(1, Object.keys(workflow.tasks).length) * 100}%` }} /></div></div><div><span className="sb-eyebrow">{t('推进模式', 'MODE')}</span><strong className="sb-mode">{workflow.paused ? t('已暂停', 'Paused') : workflow.fullManaged ? t('完全托管 · 等你体验', 'Fully managed · experience gates') : workflow.autonomous ? t('自动推进到卡点', 'Autonomous until blocked') : t('逐批手动启动', 'Manual batches')}</strong><small>{t('执行完成不等于验收通过', 'Execution is not acceptance')}</small></div><div><span className="sb-eyebrow">{t('质量关卡', 'QUALITY GATE')}</span><strong className="sb-mode">{t('独立审查 → 经理把关', 'Independent review → Manager')}</strong><small>{t('默认由你确认实际体验', 'Your experience confirmation by default')}</small></div></section>}

    {(tab === 'board' || tab === 'manager') && <section className="sb-manager-hub"><div className="sb-manager-heading"><Sparkles size={20} /><div><h2>{t('经理给你的消息', 'Your manager’s guidance')}</h2><p>{attentionTasks.length ? t('下面说明目前卡在哪里，以及你下一步能做什么。', 'See what needs attention and what to do next.') : t('经理结论与调整会保存在记录中，无需从工具日志里寻找。', 'Recommendations and changes are saved separately from tool logs.')}</p></div><button className="sb-button" onClick={() => setTab('manager')}>{t('查看经理记录', 'Manager records')}</button></div>
      {attentionTasks.slice(0, 3).map(item => { const p = workflow.tasks[item.id]; return <article className="sb-manager-message" key={item.id}><div><strong>{item.title}</strong><span className="sb-phase">{phase(p.phase)}</span></div><p>{attentionFor(item.id)?.message || p.manager?.summary || p.reviewer?.summary || t('经理尚未完成核对。点击查看处理原因。', 'The manager has not completed verification. Open details for the reason.')}</p><small>{attentionFor(item.id)?.nextStep || (p.phase === 'awaiting-user' ? t('下一步：打开任务，查看交付内容，完成体验检查后确认。', 'Next: preview the deliverable and confirm your experience.') : t('下一步：打开任务查看经理意见，可以让经理重新核对。', 'Next: open the task and ask the manager to recheck.'))}</small><button className="sb-button sb-primary" onClick={() => setSelected(item.id)}>{p.phase === 'awaiting-user' ? t('查看交付并体验', 'Preview and try') : t('查看原因与处理', 'Reason and recovery')}<ChevronRight size={16} /></button></article>; })}
      {!!inFlightTasks.length && <p className="sb-manager-running" role="status"><LoaderCircle size={15} className="sb-spin" />{t('正在推进：', 'In progress: ')}{inFlightTasks.map(item => item.title + ' · ' + phase(workflow.tasks[item.id].phase)).join('；')}{t('。完成后会在这里给出结论。', '. A recommendation will appear here when ready.')}</p>}
      {!attentionTasks.length && !inFlightTasks.length && <p className="sb-muted">{managerRecords[0]?.summary || t('尚无待处理事项。可以启动任务，或让经理起草方案。', 'Nothing needs attention. Start a task or ask for a plan.')}</p>}
      <div className="sb-managed"><div><strong>{t('完全托管', 'Fully managed')}</strong><p>{t('授权经理自动推进、客观验收、合入和限次返工，并可调整执行方法后知会你。仍保留原始目标、验收标准和写入边界；真实体验由你确认。模型与并发/返工上限不变。', 'Delegates progression, objective acceptance, integration, bounded revision and disclosed execution-method adjustments. Goals, criteria, write scope, models and limits remain unchanged; you confirm real experience.')}</p></div><button role="switch" aria-checked={workflow.fullManaged} aria-label={t('完全托管', 'Fully managed')} className={workflow.fullManaged ? 'sb-button sb-primary' : 'sb-button'} disabled={pending} onClick={() => void action('settings', { fullManaged: !workflow.fullManaged, paused: workflow.fullManaged ? workflow.paused : false }, t('托管授权已更新，经理记录已留痕', 'Delegation updated and recorded'))}>{workflow.fullManaged ? t('已开启 · 点击关闭', 'On · turn off') : t('开启完全托管', 'Enable full management')}</button></div>
    </section>}
    {tab === 'manager' && <section className="sb-manager-history sb-sheet"><h2>{t('经理记录', 'Manager records')}</h2><p className="sb-muted">{t('仅显示结论、处理建议、授权及任务调整；工具调用在任务详情中。记录持续保留，重新审查不会清空。', 'Recommendations, actions, permissions and changes are retained across re-reviews. Tool calls stay in task details.')}</p><div className="sb-manager-history-list">{managerRecords.length ? managerRecords.map(record => <article key={record.id}><div className="sb-record-heading"><time>{new Date(record.at).toLocaleString()}</time><span>{record.kind === 'task-change' ? t('执行方法已调整', 'Method changed') : record.kind === 'authorization' ? t('授权变更', 'Permission change') : record.kind === 'attention' ? t('处理建议', 'Action needed') : record.kind === 'plan' ? t('方案草稿', 'Plan draft') : t('经理结论', 'Manager recommendation')}</span></div><p className="sb-preserve">{record.summary}</p>{record.taskId && <button className="sb-button sb-small" onClick={() => setSelected(record.taskId!)}>{tasks.find(item => item.id === record.taskId)?.title || t('打开相关任务', 'Open task')}</button>}{record.after && <details><summary>{t('查看调整前后', 'Before and after')}</summary><strong>{t('之前的补充说明', 'Previous guidance')}</strong><p className="sb-preserve">{record.before || t('无补充说明', 'None')}</p><strong>{t('调整后的补充说明', 'New guidance')}</strong><p className="sb-preserve">{record.after}</p></details>}{record.assessment && <details><summary>{t('查看结论证据', 'Assessment evidence')}</summary><Review title={t('经理推荐', 'Manager recommendation')} result={record.assessment} t={t} /></details>}</article>) : <p className="sb-muted">{t('尚无经理记录。旧任务的有效结论仍可在任务详情查看。', 'No manager records yet. Existing valid assessments remain in task details.')}</p>}</div></section>}
    {tab === 'board' && <><div className="sb-board-bar"><h2>{t('任务看板', 'Task board')}<span>{sorted.length}</span></h2><div><input aria-label={t('搜索任务', 'Search tasks')} placeholder={t('搜索任务…', 'Search tasks…')} value={search} onChange={e => setSearch(e.target.value)} /><button className="sb-button" onClick={() => { setAscending(!ascending); setNotice(t('已按名称整理', 'Sorted by name')); }}>{t('按名称整理', 'Sort by name')} {ascending ? '↑' : '↓'}</button><button className="sb-button sb-primary" onClick={() => { setTab('spec'); setDraft(structuredClone(workflow)); }}><Plus size={15} />{t('生成 / 导入任务', 'Generate / import tasks')}</button></div></div>
      {!tasks.length && <div className="sb-empty"><Sparkles size={30} /><h3>{t('从一个想法开始', 'Start with an idea')}</h3><p>{t('写下你想做的事，项目经理会起草说明与任务；你确认后再开始。', 'Describe what you want. Your manager drafts the plan for your confirmation.')}</p><button className="sb-button sb-primary" onClick={() => setTab('spec')}>{t('写下原始想法', 'Describe your idea')}</button></div>}
      <DndContext sensors={sensors} onDragEnd={drop}><div className="sb-board">{lanes.map((lane, i) => { const list = sorted.filter(x => x.columnId === lane); return <Lane key={lane} id={lane} title={t(['待执行', '执行中', '审查与确认', '已完成'][i], ['Ready', 'In progress', 'Review & confirm', 'Done'][i])} count={list.length}>{list.map(item => { const p = workflow.tasks[item.id]; return <Card key={item.id} task={item} phase={phase(p?.phase || item.agentStatus)} blocked={!!p?.dependsOn.some(d => !workflow.tasks[d]?.acceptedAt || !workflow.tasks[d]?.mergedAt)} t={t} pending={pending} onMerge={p?.acceptedAt && !p.mergedAt ? () => void action('merge', { taskId: item.id }, t('已合入，相关下游任务可以启动', 'Integrated; downstream tasks unlocked')) : undefined} onClick={() => setSelected(item.id)} />; })}</Lane>; })}</div></DndContext>
      <details className="sb-activity"><summary>{t('原始工具与流程事件（高级）', 'Raw tool and workflow events (advanced)')}</summary><h2><Sparkles size={17} />{t('原始流程记录', 'Raw workflow activity')}<small>{t('原始执行事件 · 拉到最底部自动跟随', 'Actual events · scroll to bottom to follow')}</small></h2><div ref={selected ? undefined : logRef} onScroll={e => { const el = e.currentTarget; follow.current = el.scrollHeight - el.scrollTop - el.clientHeight < 30; }} className="sb-log">{workflow.events.length ? workflow.events.map(e => <div key={e.id}><time>{new Date(e.at).toLocaleTimeString()}</time><span className="sb-role-label">{e.role}</span><p>{e.content}</p></div>) : <p className="sb-muted">{t('尚未启动。请先填写想法，或选择一张任务卡。', 'Not started. Describe an idea or select a task.')}</p>}</div></details></>}
    {tab === 'spec' && <div className="sb-editor">{workflow.proposal && <PlanPreview proposal={workflow.proposal} source={workflow.importPreview?.source} projectName={project?.name} repoPath={project?.repoPath} pending={pending} t={t} onConfirm={() => void action('publish', {}, t('方案已确认，任务卡已发布', 'Plan confirmed and tasks published'))} onDiscard={() => void action('discard-proposal', {}, t('方案已丢弃，任务未变', 'Draft discarded; tasks unchanged'))} />}<section className="sb-sheet"><h2>{t('原始想法', 'Original idea')}</h2><p className="sb-muted">{t('用自己的话描述；无需懂技术。经理会将其整理成可确认的产品说明。', 'Use your own words. Your manager turns them into an understandable specification.')}</p><textarea aria-label={t('原始想法', 'Original idea')} rows={5} value={draft.idea} onChange={e => setDraft({ ...draft, idea: e.target.value })} placeholder={t('我希望做一个…用户能够…最重要的是…', 'I want to build… Users should be able to… What matters most is…')} /><div className="sb-actions"><button disabled={pending} className="sb-button" onClick={() => void action('settings', { idea: draft.idea, productSpec: draft.productSpec, technicalSpec: draft.technicalSpec }, t('需求已保存', 'Specification saved'))}>{t('保存需求', 'Save specification')}</button><button disabled={pending || !draft.idea.trim()} className="sb-button sb-primary" onClick={() => void work(async () => { await request(`/${projectId}/settings`, 'POST', { idea: draft.idea }); await request(`/${projectId}/propose`, 'POST', {}); }, t('经理已开始起草，进展会显示在记录中', 'Manager started drafting; follow the activity log'))}><Sparkles size={15} />{t('让经理起草任务方案', 'Ask manager to draft plan')}</button></div></section>
      <section className="sb-sheet"><h2>{t('产品说明 · 给用户看', 'Product specification')}</h2><textarea aria-label={t('产品说明', 'Product specification')} rows={5} value={draft.productSpec} onChange={e => setDraft({ ...draft, productSpec: e.target.value })} /><details><summary>{t('技术规格 · 给执行和审查使用', 'Technical specification')}</summary><textarea aria-label={t('技术规格', 'Technical specification')} rows={5} value={draft.technicalSpec} onChange={e => setDraft({ ...draft, technicalSpec: e.target.value })} /></details></section>

      <section className="sb-sheet"><details open={manualImportOpen} onToggle={e => setManualImportOpen(e.currentTarget.open)}><summary>{t('已有方案？手动导入 JSON', 'Already have a plan? Import JSON')}</summary><p className="sb-muted">{t('格式：productSpec、technicalSpec、tasks；每个任务包含 title、description、criteria、dependsOn（前序索引）、complexity。先预览，确认后创建任务；不调用模型。', 'Proposal format: productSpec, technicalSpec, tasks with title, description, criteria, dependsOn indices and complexity. Preview first; confirm to create tasks. No model call.')}</p><textarea aria-label={t('任务方案 JSON', 'Task plan JSON')} rows={6} value={json} onChange={e => setJson(e.target.value)} /><button className="sb-button" disabled={pending} onClick={() => void work(async () => { await request(`/${projectId}/preview`, 'POST', { proposal: JSON.parse(json) as Proposal }); setManualImportOpen(false); }, t('方案已送审，请核对后发布', 'Plan preview ready; confirm before publishing'))}>{t('预览导入方案', 'Preview import')}</button></details></section></div>}
    {tab === 'settings' && <div className="sb-editor"><input aria-label={t("搜索设置", "Search settings")} placeholder={t("搜索设置：模型、思考、接口、授权…", "Search settings: model, effort, endpoint, permissions…")} value={settingsSearch} onChange={e => setSettingsSearch(e.target.value)} /><section hidden={!matchesSetting("角色 经理 执行 审查 模型 思考 等级 自动 选档 harness model effort manager executor reviewer timeout")} className="sb-sheet"><h2>{t('三个角色，分别配置', 'Configure each role')}</h2><p className="sb-muted">{t('先确保对应工具已安装并登录。模型 ID 不限于预设；不支持的思考等级会报错，不会静默替换模型。', 'Install and authenticate each harness. Model IDs are editable. Unsupported effort fails explicitly without silently changing the model.')}</p>{(['manager', 'executor', 'reviewer'] as Role[]).map(role => <ProfileEditor key={role} name={t(...roleNames[role] as [string, string])} value={draft.roles[role]} endpoints={endpoints} t={t} onChange={p => setDraft({ ...draft, roles: { ...draft.roles, [role]: p } })} />)}</section>
      <section hidden={!matchesSetting("推进 完全托管 经理修改 授权 并发 自动 验收 合入 暂停 返工 managed manager edit concurrency authorization acceptance pause merge revision")} className="sb-sheet"><h2>{t('推进与授权', 'Progression & permissions')}</h2><div className="sb-delegation-notice"><label className="sb-check"><input type="checkbox" checked={draft.fullManaged} onChange={e => setDraft({ ...draft, fullManaged: e.target.checked, autonomous: e.target.checked, autoAccept: e.target.checked, autoMerge: e.target.checked, managerMayEdit: e.target.checked })} />{t('完全托管（一次开启下方四项授权）', 'Fully managed (enable all four permissions)')}</label><p>{t('披露式授权：经理可自行推进、客观验收、合入、限次返工及补充执行方法；每次调整留下理由与前后记录。原始目标、验收标准与写入范围不变，真实体验仍由你确认。关闭不取消已发出的调用；可使用暂停项目。', 'Disclosed delegation: progression, objective acceptance, integration, bounded revision and logged method adjustments. Goals, criteria and write scope stay unchanged. You confirm real experience. Turn off does not cancel running calls; use Pause.')}</p></div>{([['autonomous', '依赖解锁后自动推进，直到卡点', 'Auto-start unlocked tasks until blocked'], ['autoAccept', '允许客观条件全部通过后自动验收', 'Automatically accept fully verified objective criteria'], ['autoMerge', '允许已验收任务自动合入本地项目', 'Automatically integrate accepted tasks locally'], ['managerMayEdit', '允许经理调整执行方法并留痕（不改变验收标准）', 'Allow disclosed execution-method adjustments without changing criteria']] as const).map(([key, zh, en]) => <label className="sb-check" key={key}><input type="checkbox" checked={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.checked, fullManaged: false })} />{t(zh, en)}</label>)}<div className="sb-fields"><label>{t('任务并发上限', 'Task concurrency')}<input type="number" min="1" max="4" value={draft.maxConcurrency} onChange={e => setDraft({ ...draft, maxConcurrency: Number(e.target.value) })} /></label><label>{t('每任务自动返工上限', 'Automatic revision cap')}<input type="number" min="0" max="5" value={draft.maxRevisions} onChange={e => setDraft({ ...draft, maxRevisions: Number(e.target.value) })} /></label></div><label className="sb-check"><input type="checkbox" checked={draft.paused} onChange={e => setDraft({ ...draft, paused: e.target.checked })} />{t('保持项目暂停', 'Keep project paused')}</label><button disabled={pending} className="sb-button sb-primary" onClick={() => void action('settings', { roles: draft.roles, autonomous: draft.autonomous, autoAccept: draft.autoAccept, autoMerge: draft.autoMerge, managerMayEdit: draft.managerMayEdit, ...(draft.fullManaged ? { fullManaged: true } : {}), maxConcurrency: draft.maxConcurrency, maxRevisions: draft.maxRevisions, paused: draft.paused }, t('角色与授权已保存', 'Roles and permissions saved'))}>{t('保存角色与授权', 'Save roles and permissions')}</button></section>
</div>}
    {workflow.proposal && tab !== 'spec' && <div className="sb-plan-banner"><strong>{t('当前项目有一份待确认方案', 'This project has a plan awaiting confirmation')}</strong><button className="sb-button" onClick={() => setTab('spec')}>{t('查看方案', 'View plan')}</button></div>}
    {tab === 'settings' && <div hidden={!matchesSetting('AI API 凭据 密钥 授权 连接 权限 只读 送审 MCP key token access permission')}><AiAccess key={projectId} projectId={projectId} hasRepo={!!project?.repoPath} t={t} request={request} onNotice={setNotice} /></div>}
    {tab === 'guide' && <UsageGuide t={t} project={project} taskCount={Object.keys(workflow.tasks).length} integratedCount={Object.values(workflow.tasks).filter(item => item.phase === 'integrated').length} onCreate={() => setNewProject(true)} onNavigate={next => { setTab(next); setDraft(structuredClone(workflow)); }} onExample={() => { setDraft(structuredClone(workflow)); setJson(lang === 'zh' ? demoZh : demoEn); setManualImportOpen(true); setTab('spec'); setNotice(t('示例已填入，请检查方案后确认导入', 'Example loaded; check the plan before confirming import')); }} />}
    {tab === 'projects' && <div className="sb-quick-start"><div><strong>{t('第一次使用？从这里开始', 'First time? Start here')}</strong><p>{t('选择项目 → 任务方案 → 执行审查 → 体验与合入', 'Project → task plan → execution and review → experience and integration')}</p></div><button className="sb-button" onClick={() => setTab('guide')}><CircleHelp size={16} />{t('打开使用指引', 'Open getting started')}</button></div>}
    {tab === 'projects' && <ProjectHub refreshKey={hubRevision} t={t} request={request} pending={pending} phase={phase} onNotice={setNotice} onCreate={() => setNewProject(true)} onOpen={(id, taskId) => void work(async () => { setSelected(''); const loaded = await refresh(id, true, true); if (!loaded || projectRef.current !== id) return; setTab(loaded.workflow.proposal && !loaded.tasks.length ? 'spec' : 'board'); if (taskId) setSelected(taskId); }, t('项目已打开', 'Project opened'), false)} />}
    {tab === 'integrations' && <IntegrationSettings onNotice={setNotice} value={appearance} t={t} pending={pending} onSave={value => void work(async () => { setAppearance(await request<WorkbenchSettings>('/settings', 'PUT', value)); }, t('全局设置已保存', 'Global settings saved'))}>      <section className="sb-sheet"><h2>{t('添加自定义 / 本地接口', 'Custom / local endpoint')}</h2><p className="sb-muted">{t('由 OpenCode 提供工具执行能力。密钥只保存在本机服务端，读取配置时不返回密钥。', 'OpenCode provides tool execution. Keys stay in local server storage and are not returned in configuration reads.')}</p><div className="sb-fields"><label>{t('接口标识', 'Endpoint ID')}<input value={endpoint.id} onChange={e => setEndpoint({ ...endpoint, id: e.target.value })} placeholder="local-ollama" /></label><label>{t('显示名称', 'Display name')}<input value={endpoint.name} onChange={e => setEndpoint({ ...endpoint, name: e.target.value })} /></label><label>{t('协议格式', 'Protocol')}<select value={endpoint.protocol} onChange={e => setEndpoint({ ...endpoint, protocol: e.target.value as Endpoint['protocol'] })}><option value="openai">OpenAI compatible</option><option value="anthropic">Anthropic compatible</option></select></label><label>{t('接口地址', 'Base URL')}<input value={endpoint.baseUrl} onChange={e => setEndpoint({ ...endpoint, baseUrl: e.target.value })} /></label><label>{t('API 密钥（本地服务可留空）', 'API key (optional for local)')}<input type="password" autoComplete="new-password" value={endpoint.apiKey} onChange={e => setEndpoint({ ...endpoint, apiKey: e.target.value })} /></label></div><button className="sb-button" disabled={pending} onClick={() => void work(async () => { await request('/endpoints', 'PUT', endpoint); setEndpoint({ ...endpoint, apiKey: '' }); }, t('接口已保存，可在角色模型来源中选择', 'Endpoint saved; select it in role settings'))}>{t('保存接口', 'Save endpoint')}</button>{endpoints.map(e => <div className="sb-endpoint" key={e.id}><span>{e.name} · {e.protocol}</span><code>{e.baseUrl}</code><span>{e.hasKey ? t('密钥已设置', 'Key configured') : t('无密钥', 'No key')}</span><button className="sb-button sb-small" onClick={() => setEndpoint({ ...e, apiKey: undefined })}>{t('编辑', 'Edit')}</button></div>)}<p className="sb-muted">{t('ZCode、Trae、WorkBuddy、GenericAgent：后续适配；当前不会显示为已可执行。', 'ZCode, Trae, WorkBuddy, GenericAgent: future adapters; not advertised as runnable.')}</p></section></IntegrationSettings>}
    </main>
    <QuotaCard value={appearance} usesCodex={Object.values(workflow.roles).some(role => role.harness === 'codex') || Object.values(workflow.tasks).some(policy => policy.override?.harness === 'codex')} t={t} request={request} onHide={() => void work(async () => { setAppearance(await request<WorkbenchSettings>('/settings', 'PUT', { ...appearance, quotaVisibility: 'hidden' })); }, t('额度卡已隐藏，可在集成设置重新打开', 'Quota card hidden; reopen in integration settings'))} />
    {newProject && <div className="sb-modal-backdrop"><section role="dialog" aria-modal="true" aria-label={t('新建项目', 'New project')} className="sb-modal"><button className="sb-modal-close sb-icon" aria-label={t('关闭', 'Close')} onClick={() => setNewProject(false)}><X /></button><h2>{t('新建项目', 'New project')}</h2><label>{t('项目名称', 'Project name')}<input value={newName} onChange={e => setNewName(e.target.value)} /></label><label>{t('本地项目路径', 'Local project path')}<input value={newPath} onChange={e => setNewPath(e.target.value)} placeholder="E:/Projects/my-project" /></label><p className="sb-muted">{t('执行代码任务需要有初始提交的 Git 项目。任务使用独立 worktree；不会替你初始化或覆盖主目录。', 'Code execution requires a Git repository with an initial commit. Each task gets an isolated worktree.')}</p><button disabled={pending || !newName || !newPath} className="sb-button sb-primary" onClick={() => void work(async () => { const p = await api.createProject({ name: newName, repoPath: newPath, defaultAgentType: 'opencode', defaultUseWorktree: true }); await refresh(p.id, true, true); setTab('spec'); setNewProject(false); setNewName(''); setNewPath(''); }, t('项目已创建', 'Project created'), false)}>{t('创建项目', 'Create project')}</button></section></div>}
    {task && policy && <div className="sb-drawer-backdrop" onClick={() => setSelected('')}><section className="sb-drawer" role="dialog" aria-modal="true" aria-label={t('任务详情', 'Task details')} onClick={e => e.stopPropagation()}><header><div><span className="sb-eyebrow">{task.id.slice(0, 8)} · {phase(policy.phase)}</span><h2>{task.title}</h2></div><button className="sb-icon" aria-label={t('关闭任务', 'Close task')} onClick={() => setSelected('')}><X /></button></header><p className="sb-preserve">{task.description}</p><h3>{t('验收条件', 'Acceptance criteria')}</h3>{policy.criteria.map(c => <div className="sb-criterion" key={c.id}><span>{c.kind === 'human' ? t('需体验', 'Human') : t('可验证', 'Objective')}</span><p>{c.text}</p></div>)}<div className="sb-actions"><button className="sb-button sb-primary" disabled={pending} onClick={() => void action('start', { taskId: task.id, correction: reason || policy.manager?.revision || policy.reviewer?.revision }, t('已启动执行', 'Execution started'))}>{t('启动 / 按意见返工', 'Start / revise')}</button><button className="sb-button" disabled={pending} onClick={() => void action('review', { taskId: task.id }, t('已请求重新审查', 'Review requested'))}>{t('重新审查', 'Re-review')}</button><button className="sb-button" onClick={() => setDetail(task)}>{t('详细执行过程', 'Detailed execution')}</button><button className="sb-button" onClick={() => void copy(`${task.title}\n\n${task.description}${policy.managerInstructions ? '\n\n' + t('经理补充执行说明（原始范围不变）：', 'Manager execution guidance (original scope unchanged): ') + '\n' + policy.managerInstructions : ''}\n\n${t('验收条件', 'Acceptance criteria')}:\n${policy.criteria.map(c => `${c.id}: ${c.text}`).join('\n')}\n\n${t('只修改任务工作区；上游产物只读；不得自行合并或降低验收要求。', 'Only modify the task workspace; upstream artifacts are read-only. Do not merge or lower acceptance criteria.')}\n${task.worktreePath || task.repoPath || ''}${appearance.toolsDirectory ? '\n' + t('如已获准安装工具，在以下目录按工具建立子目录：', 'If tool installation is authorized, use a tool-specific subdirectory under: ') + appearance.toolsDirectory : ''}`)}>{t('复制执行交接', 'Copy handoff')}</button></div>
      <section className="sb-manager-focus"><h3><Sparkles size={18} />{t('经理给你的意见', 'Your manager’s recommendation')}</h3><div className="sb-live-state"><strong>{t('实际推进状态', 'Actual workflow state')}</strong><p>{t('本任务：', 'This task: ')}{phase(policy.phase)}</p>{policy.dependsOn.map(id => <p key={id}>{t('上游：', 'Upstream: ')}{tasks.find(item => item.id === id)?.title || id.slice(0,8)} · {phase(workflow.tasks[id]?.phase || 'ready')}</p>)}</div>{taskAttention && <div className="sb-recovery" role="status"><strong>{t('当前卡点', 'Current blocker')}</strong><p>{taskAttention.message}</p><p>{taskAttention.nextStep}</p><button disabled={pending} className="sb-button sb-primary" onClick={() => void action('review', { taskId: task.id }, t('经理已开始重新核对，结论会出现在经理记录', 'Manager is rechecking; follow Manager records'))}>{t('让经理重新核对', 'Ask manager to recheck')}</button></div>}<Review title={t('经理推荐', 'Manager recommendation')} result={policy.manager} t={t} />{policy.managerInstructions && <details><summary>{t('经理调整后的执行说明', 'Manager execution guidance')}</summary><p className="sb-preserve">{policy.managerInstructions}</p></details>}</section><details><summary>{t('独立审查与技术证据', 'Independent technical review')}</summary><Review title={t('独立审查', 'Independent review')} result={policy.reviewer} t={t} /></details><section className="sb-delivery"><h3>{t('交付内容 · 在这里体验', 'Deliverable · try it here')}</h3><button className="sb-button" disabled={pending || !task.worktreePath} onClick={() => void work(async () => { const origin = projectId; const selectedTask = task.id; const files = await request<{ path: string; content?: string; note?: string }[]>('/' + origin + '/tasks/' + selectedTask + '/artifacts'); if (projectRef.current === origin && selectionRef.current === selectedTask) setArtifacts(files); }, t('交付内容已显示，下方可以阅读', 'Deliverable loaded below'))}>{t('查看交付文件', 'Preview deliverable')}</button>{artifacts && <Suspense fallback={<p>{t('正在打开交付内容…', 'Loading preview…')}</p>}><ArtifactPreview files={artifacts} /></Suspense>}</section>
      {policy.phase === 'awaiting-user' && <div className="sb-human"><p>{t('技术审查已通过。请完成上面的体验检查，再确认。', 'Technical reviews passed. Complete the experience checks before confirming.')}</p><button disabled={pending} className="sb-button sb-primary" onClick={() => void action('accept', { taskId: task.id }, workflow.fullManaged && !workflow.paused ? t('体验已确认，经理会继续合入并推进', 'Experience confirmed; manager will integrate and continue') : t('已确认验收，下一步可合入项目', 'Accepted; ready for integration'))}><Check size={16} />{t('我已确认，验收通过', 'Confirm acceptance')}</button></div>}
      {policy.acceptedAt && !policy.mergedAt && <button disabled={pending} className="sb-button sb-primary" onClick={() => void action('merge', { taskId: task.id }, t('已合入，相关下游任务可以启动', 'Integrated; downstream tasks unlocked'))}>{t('合入项目并解锁下游', 'Integrate and unlock downstream')}</button>}
      <label>{t('反馈 / 返工 / 重新打开原因', 'Feedback / revision / reopen reason')}<textarea rows={3} value={reason} onChange={e => setReason(e.target.value)} /></label><button disabled={pending || !reason.trim()} className="sb-button" onClick={() => void action('reopen', { taskId: task.id, reason }, t('任务已重新打开，相关下游已暂停', 'Reopened; dependent work paused'))}>{t('重新打开 / 撤回验收', 'Reopen / revoke acceptance')}</button>
      <details><summary>{t('修订任务与手动模型覆盖', 'Edit task & model override')}</summary>{edit && <><label>{t('任务名称', 'Task title')}<input value={edit.title} onChange={e => setEdit({ ...edit, title: e.target.value })} /></label><label>{t('执行说明', 'Instructions')}<textarea rows={4} value={edit.description} onChange={e => setEdit({ ...edit, description: e.target.value })} /></label>{edit.criteria.map((c, i) => <div key={i} className="sb-candidate"><input aria-label={t('验收说明', 'Criterion')} value={c.text} onChange={e => setEdit({ ...edit, criteria: edit.criteria.map((v, n) => n === i ? { ...v, text: e.target.value } : v) })} /><select value={c.kind} aria-label={t('验收类型', 'Criterion type')} onChange={e => setEdit({ ...edit, criteria: edit.criteria.map((v, n) => n === i ? { ...v, kind: e.target.value as Criterion['kind'] } : v) })}><option value="objective">{t('客观验证', 'Objective')}</option><option value="human">{t('用户体验', 'Human')}</option></select></div>)}<button className="sb-button sb-small" onClick={() => setEdit({ ...edit, criteria: [...edit.criteria, { id: `A${Date.now()}`, text: '', kind: 'objective' }] })}>{t('添加验收条件', 'Add criterion')}</button><label className="sb-check"><input type="checkbox" checked={!!edit.override} onChange={e => setEdit({ ...edit, override: e.target.checked ? { ...workflow.roles.executor, auto: false } : undefined })} />{t('此任务手动指定模型（优先于经理自动选档）', 'Override executor model for this task')}</label>{edit.override && <ProfileEditor name={t('此任务执行配置', 'Task executor override')} value={edit.override} endpoints={endpoints} t={t} onChange={override => setEdit({ ...edit, override })} />}<button disabled={pending} className="sb-button" onClick={() => void action('edit-task', { taskId: task.id, ...edit }, t('任务已修订，旧验收已失效', 'Task revised; previous acceptance invalidated'))}>{t('保存修订', 'Save revision')}</button></>}</details>
      <details><summary>{t('原始执行过程（高级）', 'Raw execution activity (advanced)')}</summary><div ref={logRef} className="sb-log sb-task-log" onScroll={e => { const el = e.currentTarget; follow.current = el.scrollHeight - el.scrollTop - el.clientHeight < 30; }}>{[...events.map(e => ({ at: e.timestamp, content: e.content, role: 'executor' })), ...workflow.events.filter(e => e.taskId === selected)].sort((a, b) => a.at - b.at).map((e, i) => <div key={i}><time>{new Date(e.at).toLocaleTimeString()}</time><span className="sb-role-label">{e.role}</span><p>{e.content}</p></div>)}</div><small className="sb-muted">{t('工作目录：', 'Workspace: ')}{task.worktreePath || t('执行后创建', 'Created on execution')}</small></details>
    </section></div>}
    {detail && <Suspense fallback={<div className="sb-pending">{t('正在打开详细过程…', 'Opening detailed view…')}</div>}><AgentPanel task={tasks.find(t => t.id === detail.id) || detail} translate={t} theme="light" onClose={() => setDetail(null)} /></Suspense>}
    {pending && <div className="sb-pending"><LoaderCircle size={15} className="sb-spin" />{t('处理中…', 'Working…')}</div>}
  </div>;
}
